out [any + str]
hlt [exit_code]
mov [mutable] [any] [any]
add [mutable] [any] [any]
sub [mutable] [any] [any]
div [mutable] [any] [any]
mul [mutable] [any] [any]
cmp [any] [any]
jmp [label]
je [any] [any]
jne [any] [any]
jg [any] [any]
jl [any] [any]
jge [any] [any]
jle [any] [any]
call [label]
ret